### ISSUE TITLE
Commit cannot be loaded

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/contribution-tool#137]
If I try to load https://github.com/Kissaki/contrib-declarations/commit/9858e864597617c94be13c3a7dedaec00053c2a4 in the contribution tool, I get stuck on the “Loading declaration…” page forever.

**Comment by martinratinaud** [comment]
Can you please share the url of the contribution tool?

The commit you share is a declaration commit when the contribution tool waits for a versions commit. Maybe that's the problem?

**Comment by MattiSG** [comment]
[I can't because, precisely, ](https://contribute.opentermsarchive.org/service?commit=https://github.com/Kissaki/contrib-declarations/commit/9858e864597617c94be13c3a7dedaec00053c2a4)

**Comment by MattiSG** [comment]
> The commit you share is a declaration commit when the contribution tool waits for a versions commit. Maybe that's the problem?

Ah okay, certainly then! I hoped to review a suggested change but I can't in this case. Thanks!
