### ISSUE TITLE
Can't cancel a significant/insignificant part selection

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/contribution-tool#148]
### Overview
We need to have a UI feature to undo/cancel the effect of the _select button_ if you click it by mistake so that users can have a good user experience
Right now if you click on select by mistake, you either have to remove the effect by pressing `ESC` button or selecting a part then deleting it

**Comment by MattiSG** [comment]
This is done with the 🗑️ icon next to the selector 🙂
