### ISSUE TITLE
Typo in Thank you Page

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/contribution-tool#150]
<img width="898" alt="Screen Shot 2023-07-20 at 13 50 01" src="https://github.com/OpenTermsArchive/contribution-tool/assets/41474439/680894b2-ee0d-4c5e-94a3-d4a35c023348">

**Comment by MattiSG** [comment]
Good catch! Could you please maybe open a pull request to correct it? 🙂

**Comment by emmanuellar** [comment]
> Good catch! Could you please maybe open a pull request to correct it? 🙂

Yes, definitely.
