### ISSUE TITLE
404

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/contribution-tool#36]
Trying to load the folllowing document `https://www.airtransat.com/fr-FR/avis-juridiques/conditions-de-vente`  i get a 404 error.

![image](https://user-images.githubusercontent.com/364319/157699516-7528457a-ffbd-4caf-b3eb-d82af223d1b8.png)

**Comment by martinratinaud** [comment]
It is now a 403 and I have the same on my local, so it's not relevent anymore
