### ISSUE TITLE
Handle resubmitting a new json file when reviewing

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/contribution-tool#67]
After the first batch of documents added by Open Evidence, it appears that everytime a selector has to be changed to make it more resilient, this has to be done by manually changing the file, either on local or directly on github.

This is not very time consuming but still could be improved.

## Proposal

When a branch with the same name already exists, retrieve the current version of the file, modify it and add a new commit to the branch

**Comment by MattiSG** [comment]
Fixed by #68, close when deployed.
