### ISSUE TITLE
Can't select in page `Selector was not found`

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/contribution-tool#92]
- [bol.com](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Acceptable%20Use%20Policy&expertMode=true&name=bol.com&url=https%3A%2F%2Fwww.bol.com%2Fbe%2Fnl%2Fm%2Fovereenkomst-verkoper-zakelijk%2F&hiddenCssClass[]=modalWindow)

```
Uncaught Error: Selector was not found.
    at finder (css-path-finder.js:40:11)
    at HTMLBodyElement.onClick (injected-script.js:94:17)
```

**Comment by martinratinaud** [comment]
For this one, selection does not work because the DOM has two identical ids `modalWindow` which makes the selector crash.

I added a fallback in such case to not have to change the finder library we use. This library is indeed the best in this [benchmark](https://github.com/fczbkk/css-selector-generator-benchmark). For now I don't want to spend so much time on this as it happens really rarely

**Comment by MattiSG** [comment]
Thanks for this description! Do we intend to give feedback to the user in such a case? Can this happen when the user clicks on the page or only if a selector is loaded in the UI from the description?

**Comment by martinratinaud** [comment]
This should not happen anymore as if it does, `Unknown selector` will be written in the input (which I agree is not really UI friendly)

And sorry but I did not get your question `Can this happen when the user clicks on the page or only if a selector is loaded in the UI from the description?`
