### ISSUE TITLE
Remove class from DOM 

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/contribution-tool#98]
Sometimes, a class is preventing the page from displaying normally.

An example is with `bol.com` where we should remove the class `.modal--is-open`. It should normally be removed by the cookie panel handler, but in this specific case, there are 2 modal windows :-(

We could add a new expert tool in the same flavor as `Hidden element(s)` where we could enter a class to be removed from all nodes in the iframe.

- [bol.com](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Acceptable%20Use%20Policy&expertMode=true&name=bol.com&url=https%3A%2F%2Fwww.bol.com%2Fbe%2Fnl%2Fm%2Fovereenkomst-verkoper-zakelijk%2F&hiddenCssClass[]=modalWindow)

@clementbiron what do you think?

**Comment by MattiSG** [comment]
Isn't that too much of an edge case to handle in the UI?

**Comment by martinratinaud** [comment]
The contribution tool is meant to ease the adding and fixing of declarations.
For now, if you go directly in the dom and remove the class, everytime you change a selector, page gets reloaded (as snapshot might be different) and your change is gone, making it very annoying and impossible for non technical user to do so.

With that kind of feature, in case such a document is difficult to handle, a technical person can do this modification and send the URL to the contributor for him to add easily the document.

I agree this is not often, but everytime it happens, it's a bit problematic.

Feel free to close if you do not find it relevant enough, but be also aware that developing this would not be really difficult also

**Comment by clementbiron** [comment]
It's seems not necessary to me that common users can handle this kind of edge case. Indeed as a technical team it sometimes cool be useful. 

So in my opinion, while waiting for a clearer solution to separate the technical / non-technical interfaces
we should do every we can to keep the contribution tool as simple as we can.

**Comment by martinratinaud** [comment]
Ok then let's close it and we'll see if it happens too often
